name: Daily AI News to ChatWork

on:
  schedule:
    # 毎日 日本時間 午前9時に実行 (UTC 0時 = JST 9時)
    # 月曜日〜金曜日のみ実行
    - cron: '0 0 * * 1-5'
  workflow_dispatch: # 手動実行も可能

jobs:
  send-ai-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run AI news script
      env:
        CHATWORK_TOKEN: ${{ secrets.CHATWORK_TOKEN }}
        CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
      run: python chatworks.py
      
    - name: Log completion
      run: echo "AI news script completed successfully"
